Repository Undefined-Hub/Classtro, pull requests merged in 2025-09, with the labels that each got.

#9 UI: Redesign landing page with responsive layout and new hero section
  frontend/public/image.webp
  frontend/src/components/Details.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Hero.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Landing.jsx
Labels: enhancement

#10 Deployment configurations
  backend/app.js
  backend/config/Passport.js
  frontend/vercel.json
Labels: hotfix

#17 Real-Time Q&A System + Auth & Deployment Enhancements
  backend/services/emailService.js
  frontend/src/App.jsx
  frontend/src/hooks/useDebounce.js
  frontend/src/pages/Host/AnalyticsPage.jsx
  frontend/src/pages/Host/SessionWorkspace.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
  frontend/src/pages/VerifyAndRole.jsx
Labels: enhancement, hotfix

#18 feat: UI/Polls-QnA, Bug Fixes, Flow Changes and overall UI/UX Improved
  backend/controllers/qnaController.js
  backend/models/Question.js
  backend/socket.js
  frontend/src/components/Host/sessionWorkspace/QAManager.jsx
  frontend/src/components/Host/sessionWorkspace/QuickActions.jsx
  frontend/src/components/Participant/AskQuestionModal.jsx
  frontend/src/components/Participant/ParticipantLivePoll.jsx
  frontend/src/components/Participant/ParticipantQnA.jsx
  frontend/src/components/Participant/QuestionsPanel.jsx
  frontend/src/components/Participant/SessionHeader.jsx
  frontend/src/components/Participant/WelcomeContent.jsx
  frontend/src/pages/Host/SessionWorkspace.jsx
  frontend/src/pages/Participant/ParticipantSession.jsx
Labels: bug, enhancement, feature, hotfix

#20 HotFix: Fixed the ParticipanCount Issue finally
  backend/controllers/sessionController.js
  backend/models/Session.js
  frontend/src/components/Host/sessionWorkspace/ParticipantList.jsx
  frontend/src/components/Participant/Header.jsx
  frontend/src/components/ProfileImageOrInitials.jsx
  frontend/src/pages/Participant/ParticipantSession.jsx
Labels: hotfix

#21 fix: Unnecessary Socket disconnect/reconnect in ParticipantSession fixed
  frontend/src/context/ParticipantSessionContext.jsx
  frontend/src/pages/Participant/ParticipantSession.jsx
Labels: enhancement, Fix

#23 hotfix(qna): Added debouncing to ask question button, can't be spammed
  frontend/src/pages/Participant/ParticipantSession.jsx
Labels: hotfix

#24 Fix & Enhancements: Participant Session Stability, UI Improvements, and Spam Protection
  backend/controllers/qnaController.js
  backend/controllers/sessionController.js
  backend/models/Question.js
  backend/models/Session.js
  backend/services/emailService.js
  backend/socket.js
  frontend/src/App.jsx
  frontend/src/components/Analytics/SessionHeader.jsx
  frontend/src/components/Host/sessionWorkspace/MainContent.jsx
  frontend/src/components/Host/sessionWorkspace/ParticipantList.jsx
  frontend/src/components/Host/sessionWorkspace/PastPolls.jsx
  frontend/src/components/Host/sessionWorkspace/PollManager.jsx
  frontend/src/components/Host/sessionWorkspace/QAManager.jsx
  frontend/src/components/Host/sessionWorkspace/QuickActions.jsx
  frontend/src/components/Host/sessionWorkspace/SessionHeader.jsx
  frontend/src/components/Participant/AskQuestionModal.jsx
  frontend/src/components/Participant/Header.jsx
  frontend/src/components/Participant/JoinSessionTab.jsx
  frontend/src/components/Participant/ParticipantLivePoll.jsx
  frontend/src/components/Participant/ParticipantQnA.jsx
  frontend/src/components/Participant/QuestionsPanel.jsx
  frontend/src/components/Participant/SessionHeader.jsx
  frontend/src/components/Participant/WelcomeContent.jsx
  frontend/src/components/ProfileImageOrInitials.jsx
  frontend/src/context/ParticipantSessionContext.jsx
  frontend/src/hooks/useDebounce.js
  frontend/src/pages/Host/AnalyticsPage.jsx
  frontend/src/pages/Host/DashboardPage.jsx
  frontend/src/pages/Host/SessionWorkspace.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Participant/ParticipantHome.jsx
  frontend/src/pages/Participant/ParticipantSession.jsx
  frontend/src/pages/Register.jsx
  frontend/src/pages/VerifyAndRole.jsx
Labels: enhancement, Fix

#25 chore: add favicon and app icons setup
  frontend/index.html
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-96x96.png
  frontend/public/favicon.ico
  frontend/public/favicon.svg
  frontend/public/site.webmanifest
  frontend/public/vite.svg
  frontend/public/web-app-manifest-192x192.png
  frontend/public/web-app-manifest-512x512.png
  frontend/src/assets/classtro.png
  frontend/src/assets/react.svg
  frontend/src/components/Navbar.jsx
Labels: enhancement

#26 style: Favicon changed (#25)
  frontend/index.html
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-96x96.png
  frontend/public/favicon.ico
  frontend/public/favicon.svg
  frontend/public/site.webmanifest
  frontend/public/vite.svg
  frontend/public/web-app-manifest-192x192.png
  frontend/public/web-app-manifest-512x512.png
  frontend/src/assets/classtro.png
  frontend/src/assets/react.svg
  frontend/src/components/Navbar.jsx
Labels: enhancement

#27 Nothing just something happend forget about it
  backend/socket.js
  frontend/src/components/ProfileImageOrInitials.jsx
  frontend/src/context/HostSessionContext.jsx
  frontend/src/pages/Host/SessionWorkspace.jsx
Labels: Fix
